version: '3'
services:
  webphp:
    image: wordpress:php7.3
    ports:
      - "80:80"
    volumes:
      - ./codigo:/var/www/html
    environment:
      WORDPRESS_DB_HOST: dbmysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234x
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    links:
      - dbmysql
  dbmysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234x
      - MYSQL_DATABASE=wordpress
volumes:
  dbdata:

