version: '3'
services:
  webphp:
    build: image/
    image: edersondev/wordpress:php7.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./codigo:/var/www/html
    environment:
      WORDPRESS_DB_HOST: dbmysql
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    links:
      - dbmysql
      - memcached
  dbmysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  memcached:
    image: memcached:1.5-alpine
    ports:
     - "11211:11211"
volumes:
  dbdata:
